# Generated by Django 5.2.3 on 2026-06-23 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_backfill_source_unavailable_analysis_jobs"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baseline_score_threshold",
                    models.FloatField(
                        default=0.55,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "min_description_chars",
                    models.PositiveSmallIntegerField(
                        default=80,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_endogenic_alternative_chars",
                    models.PositiveSmallIntegerField(
                        default=20,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_source_title_chars",
                    models.PositiveSmallIntegerField(
                        default=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_observed_feature_chars",
                    models.PositiveSmallIntegerField(
                        default=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_diameter_km",
                    models.FloatField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "max_diameter_km",
                    models.FloatField(
                        default=5000,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                    ),
                ),
                (
                    "duplicate_distance_fraction",
                    models.FloatField(
                        default=0.25,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "duplicate_min_distance_km",
                    models.FloatField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("require_terms_confirmed", models.BooleanField(default=True)),
                ("require_unique_study_candidate", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Review configuration",
                "verbose_name_plural": "Review configuration",
            },
        ),
    ]
